// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in storage-app/ent/runtime.go

const (
	Version = "v0.12.4-0.20230602064104-79820a3c93c9"           // Version of ent codegen.
	Sum     = "h1:vlEnWtl9lCiJIhabRy0vVis3O5xzp9odOPrPczmuQbE=" // Sum of ent codegen.
)
